// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/PortfolioNAV.proto
// Protobuf Java Version: 4.29.1

package model;

public final class PortfolioNAVOuterClass {
	private PortfolioNAVOuterClass() {
	}

	static {
		com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
				com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
				/* major= */ 4, /* minor= */ 29, /* patch= */ 1, /* suffix= */ "",
				PortfolioNAVOuterClass.class.getName());
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
	}

	public interface HoldingNAVOrBuilder extends
			// @@protoc_insertion_point(interface_extends:model.HoldingNAV)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>string symbol = 1;</code>
		 * 
		 * @return The symbol.
		 */
		java.lang.String getSymbol();

		/**
		 * <code>string symbol = 1;</code>
		 * 
		 * @return The bytes for symbol.
		 */
		com.google.protobuf.ByteString getSymbolBytes();

		/**
		 * <code>double price = 2;</code>
		 * 
		 * @return The price.
		 */
		double getPrice();

		/**
		 * <code>double quantity = 3;</code>
		 * 
		 * @return The quantity.
		 */
		double getQuantity();

		/**
		 * <code>double value = 4;</code>
		 * 
		 * @return The value.
		 */
		double getValue();
	}

	/**
	 * Protobuf type {@code model.HoldingNAV}
	 */
	public static final class HoldingNAV extends com.google.protobuf.GeneratedMessage implements
			// @@protoc_insertion_point(message_implements:model.HoldingNAV)
			HoldingNAVOrBuilder {
		private static final long serialVersionUID = 0L;
		static {
			com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
					com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
					/* major= */ 4, /* minor= */ 29, /* patch= */ 1,
					/* suffix= */ "", HoldingNAV.class.getName());
		}

		// Use HoldingNAV.newBuilder() to construct.
		private HoldingNAV(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
			super(builder);
		}

		private HoldingNAV() {
			symbol_ = "";
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return model.PortfolioNAVOuterClass.internal_static_model_HoldingNAV_descriptor;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return model.PortfolioNAVOuterClass.internal_static_model_HoldingNAV_fieldAccessorTable
					.ensureFieldAccessorsInitialized(model.PortfolioNAVOuterClass.HoldingNAV.class,
							model.PortfolioNAVOuterClass.HoldingNAV.Builder.class);
		}

		public static final int SYMBOL_FIELD_NUMBER = 1;
		@SuppressWarnings("serial")
		private volatile java.lang.Object symbol_ = "";

		/**
		 * <code>string symbol = 1;</code>
		 * 
		 * @return The symbol.
		 */
		@java.lang.Override
		public java.lang.String getSymbol() {
			java.lang.Object ref = symbol_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				symbol_ = s;
				return s;
			}
		}

		/**
		 * <code>string symbol = 1;</code>
		 * 
		 * @return The bytes for symbol.
		 */
		@java.lang.Override
		public com.google.protobuf.ByteString getSymbolBytes() {
			java.lang.Object ref = symbol_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				symbol_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int PRICE_FIELD_NUMBER = 2;
		private double price_ = 0D;

		/**
		 * <code>double price = 2;</code>
		 * 
		 * @return The price.
		 */
		@java.lang.Override
		public double getPrice() {
			return price_;
		}

		public static final int QUANTITY_FIELD_NUMBER = 3;
		private double quantity_ = 0D;

		/**
		 * <code>double quantity = 3;</code>
		 * 
		 * @return The quantity.
		 */
		@java.lang.Override
		public double getQuantity() {
			return quantity_;
		}

		public static final int VALUE_FIELD_NUMBER = 4;
		private double value_ = 0D;

		/**
		 * <code>double value = 4;</code>
		 * 
		 * @return The value.
		 */
		@java.lang.Override
		public double getValue() {
			return value_;
		}

		private byte memoizedIsInitialized = -1;

		@java.lang.Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			memoizedIsInitialized = 1;
			return true;
		}

		@java.lang.Override
		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			if (!com.google.protobuf.GeneratedMessage.isStringEmpty(symbol_)) {
				com.google.protobuf.GeneratedMessage.writeString(output, 1, symbol_);
			}
			if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
				output.writeDouble(2, price_);
			}
			if (java.lang.Double.doubleToRawLongBits(quantity_) != 0) {
				output.writeDouble(3, quantity_);
			}
			if (java.lang.Double.doubleToRawLongBits(value_) != 0) {
				output.writeDouble(4, value_);
			}
			getUnknownFields().writeTo(output);
		}

		@java.lang.Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1)
				return size;

			size = 0;
			if (!com.google.protobuf.GeneratedMessage.isStringEmpty(symbol_)) {
				size += com.google.protobuf.GeneratedMessage.computeStringSize(1, symbol_);
			}
			if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
				size += com.google.protobuf.CodedOutputStream.computeDoubleSize(2, price_);
			}
			if (java.lang.Double.doubleToRawLongBits(quantity_) != 0) {
				size += com.google.protobuf.CodedOutputStream.computeDoubleSize(3, quantity_);
			}
			if (java.lang.Double.doubleToRawLongBits(value_) != 0) {
				size += com.google.protobuf.CodedOutputStream.computeDoubleSize(4, value_);
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof model.PortfolioNAVOuterClass.HoldingNAV)) {
				return super.equals(obj);
			}
			model.PortfolioNAVOuterClass.HoldingNAV other = (model.PortfolioNAVOuterClass.HoldingNAV) obj;

			if (!getSymbol().equals(other.getSymbol()))
				return false;
			if (java.lang.Double.doubleToLongBits(getPrice()) != java.lang.Double.doubleToLongBits(other.getPrice()))
				return false;
			if (java.lang.Double.doubleToLongBits(getQuantity()) != java.lang.Double
					.doubleToLongBits(other.getQuantity()))
				return false;
			if (java.lang.Double.doubleToLongBits(getValue()) != java.lang.Double.doubleToLongBits(other.getValue()))
				return false;
			if (!getUnknownFields().equals(other.getUnknownFields()))
				return false;
			return true;
		}

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
			hash = (53 * hash) + getSymbol().hashCode();
			hash = (37 * hash) + PRICE_FIELD_NUMBER;
			hash = (53 * hash) + com.google.protobuf.Internal.hashLong(java.lang.Double.doubleToLongBits(getPrice()));
			hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
			hash = (53 * hash)
					+ com.google.protobuf.Internal.hashLong(java.lang.Double.doubleToLongBits(getQuantity()));
			hash = (37 * hash) + VALUE_FIELD_NUMBER;
			hash = (53 * hash) + com.google.protobuf.Internal.hashLong(java.lang.Double.doubleToLongBits(getValue()));
			hash = (29 * hash) + getUnknownFields().hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static model.PortfolioNAVOuterClass.HoldingNAV parseFrom(java.nio.ByteBuffer data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static model.PortfolioNAVOuterClass.HoldingNAV parseFrom(java.nio.ByteBuffer data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static model.PortfolioNAVOuterClass.HoldingNAV parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static model.PortfolioNAVOuterClass.HoldingNAV parseFrom(com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static model.PortfolioNAVOuterClass.HoldingNAV parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static model.PortfolioNAVOuterClass.HoldingNAV parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static model.PortfolioNAVOuterClass.HoldingNAV parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
		}

		public static model.PortfolioNAVOuterClass.HoldingNAV parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static model.PortfolioNAVOuterClass.HoldingNAV parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
		}

		public static model.PortfolioNAVOuterClass.HoldingNAV parseDelimitedFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
		}

		public static model.PortfolioNAVOuterClass.HoldingNAV parseFrom(com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
		}

		public static model.PortfolioNAVOuterClass.HoldingNAV parseFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
		}

		@java.lang.Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(model.PortfolioNAVOuterClass.HoldingNAV prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		@java.lang.Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code model.HoldingNAV}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:model.HoldingNAV)
				model.PortfolioNAVOuterClass.HoldingNAVOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return model.PortfolioNAVOuterClass.internal_static_model_HoldingNAV_descriptor;
			}

			@java.lang.Override
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return model.PortfolioNAVOuterClass.internal_static_model_HoldingNAV_fieldAccessorTable
						.ensureFieldAccessorsInitialized(model.PortfolioNAVOuterClass.HoldingNAV.class,
								model.PortfolioNAVOuterClass.HoldingNAV.Builder.class);
			}

			// Construct using
			// model.PortfolioNAVOuterClass.HoldingNAV.newBuilder()
			private Builder() {

			}

			private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				super(parent);

			}

			@java.lang.Override
			public Builder clear() {
				super.clear();
				bitField0_ = 0;
				symbol_ = "";
				price_ = 0D;
				quantity_ = 0D;
				value_ = 0D;
				return this;
			}

			@java.lang.Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return model.PortfolioNAVOuterClass.internal_static_model_HoldingNAV_descriptor;
			}

			@java.lang.Override
			public model.PortfolioNAVOuterClass.HoldingNAV getDefaultInstanceForType() {
				return model.PortfolioNAVOuterClass.HoldingNAV.getDefaultInstance();
			}

			@java.lang.Override
			public model.PortfolioNAVOuterClass.HoldingNAV build() {
				model.PortfolioNAVOuterClass.HoldingNAV result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@java.lang.Override
			public model.PortfolioNAVOuterClass.HoldingNAV buildPartial() {
				model.PortfolioNAVOuterClass.HoldingNAV result = new model.PortfolioNAVOuterClass.HoldingNAV(this);
				if (bitField0_ != 0) {
					buildPartial0(result);
				}
				onBuilt();
				return result;
			}

			private void buildPartial0(model.PortfolioNAVOuterClass.HoldingNAV result) {
				int from_bitField0_ = bitField0_;
				if (((from_bitField0_ & 0x00000001) != 0)) {
					result.symbol_ = symbol_;
				}
				if (((from_bitField0_ & 0x00000002) != 0)) {
					result.price_ = price_;
				}
				if (((from_bitField0_ & 0x00000004) != 0)) {
					result.quantity_ = quantity_;
				}
				if (((from_bitField0_ & 0x00000008) != 0)) {
					result.value_ = value_;
				}
			}

			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof model.PortfolioNAVOuterClass.HoldingNAV) {
					return mergeFrom((model.PortfolioNAVOuterClass.HoldingNAV) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(model.PortfolioNAVOuterClass.HoldingNAV other) {
				if (other == model.PortfolioNAVOuterClass.HoldingNAV.getDefaultInstance())
					return this;
				if (!other.getSymbol().isEmpty()) {
					symbol_ = other.symbol_;
					bitField0_ |= 0x00000001;
					onChanged();
				}
				if (other.getPrice() != 0D) {
					setPrice(other.getPrice());
				}
				if (other.getQuantity() != 0D) {
					setQuantity(other.getQuantity());
				}
				if (other.getValue() != 0D) {
					setValue(other.getValue());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				onChanged();
				return this;
			}

			@java.lang.Override
			public final boolean isInitialized() {
				return true;
			}

			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				if (extensionRegistry == null) {
					throw new java.lang.NullPointerException();
				}
				try {
					boolean done = false;
					while (!done) {
						int tag = input.readTag();
						switch (tag) {
						case 0:
							done = true;
							break;
						case 10: {
							symbol_ = input.readStringRequireUtf8();
							bitField0_ |= 0x00000001;
							break;
						} // case 10
						case 17: {
							price_ = input.readDouble();
							bitField0_ |= 0x00000002;
							break;
						} // case 17
						case 25: {
							quantity_ = input.readDouble();
							bitField0_ |= 0x00000004;
							break;
						} // case 25
						case 33: {
							value_ = input.readDouble();
							bitField0_ |= 0x00000008;
							break;
						} // case 33
						default: {
							if (!super.parseUnknownField(input, extensionRegistry, tag)) {
								done = true; // was an endgroup tag
							}
							break;
						} // default:
						} // switch (tag)
					} // while (!done)
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.unwrapIOException();
				} finally {
					onChanged();
				} // finally
				return this;
			}

			private int bitField0_;

			private java.lang.Object symbol_ = "";

			/**
			 * <code>string symbol = 1;</code>
			 * 
			 * @return The symbol.
			 */
			public java.lang.String getSymbol() {
				java.lang.Object ref = symbol_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					symbol_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string symbol = 1;</code>
			 * 
			 * @return The bytes for symbol.
			 */
			public com.google.protobuf.ByteString getSymbolBytes() {
				java.lang.Object ref = symbol_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					symbol_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string symbol = 1;</code>
			 * 
			 * @param value
			 *            The symbol to set.
			 * @return This builder for chaining.
			 */
			public Builder setSymbol(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				symbol_ = value;
				bitField0_ |= 0x00000001;
				onChanged();
				return this;
			}

			/**
			 * <code>string symbol = 1;</code>
			 * 
			 * @return This builder for chaining.
			 */
			public Builder clearSymbol() {
				symbol_ = getDefaultInstance().getSymbol();
				bitField0_ = (bitField0_ & ~0x00000001);
				onChanged();
				return this;
			}

			/**
			 * <code>string symbol = 1;</code>
			 * 
			 * @param value
			 *            The bytes for symbol to set.
			 * @return This builder for chaining.
			 */
			public Builder setSymbolBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);
				symbol_ = value;
				bitField0_ |= 0x00000001;
				onChanged();
				return this;
			}

			private double price_;

			/**
			 * <code>double price = 2;</code>
			 * 
			 * @return The price.
			 */
			@java.lang.Override
			public double getPrice() {
				return price_;
			}

			/**
			 * <code>double price = 2;</code>
			 * 
			 * @param value
			 *            The price to set.
			 * @return This builder for chaining.
			 */
			public Builder setPrice(double value) {

				price_ = value;
				bitField0_ |= 0x00000002;
				onChanged();
				return this;
			}

			/**
			 * <code>double price = 2;</code>
			 * 
			 * @return This builder for chaining.
			 */
			public Builder clearPrice() {
				bitField0_ = (bitField0_ & ~0x00000002);
				price_ = 0D;
				onChanged();
				return this;
			}

			private double quantity_;

			/**
			 * <code>double quantity = 3;</code>
			 * 
			 * @return The quantity.
			 */
			@java.lang.Override
			public double getQuantity() {
				return quantity_;
			}

			/**
			 * <code>double quantity = 3;</code>
			 * 
			 * @param value
			 *            The quantity to set.
			 * @return This builder for chaining.
			 */
			public Builder setQuantity(double value) {

				quantity_ = value;
				bitField0_ |= 0x00000004;
				onChanged();
				return this;
			}

			/**
			 * <code>double quantity = 3;</code>
			 * 
			 * @return This builder for chaining.
			 */
			public Builder clearQuantity() {
				bitField0_ = (bitField0_ & ~0x00000004);
				quantity_ = 0D;
				onChanged();
				return this;
			}

			private double value_;

			/**
			 * <code>double value = 4;</code>
			 * 
			 * @return The value.
			 */
			@java.lang.Override
			public double getValue() {
				return value_;
			}

			/**
			 * <code>double value = 4;</code>
			 * 
			 * @param value
			 *            The value to set.
			 * @return This builder for chaining.
			 */
			public Builder setValue(double value) {

				value_ = value;
				bitField0_ |= 0x00000008;
				onChanged();
				return this;
			}

			/**
			 * <code>double value = 4;</code>
			 * 
			 * @return This builder for chaining.
			 */
			public Builder clearValue() {
				bitField0_ = (bitField0_ & ~0x00000008);
				value_ = 0D;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:model.HoldingNAV)
		}

		// @@protoc_insertion_point(class_scope:model.HoldingNAV)
		private static final model.PortfolioNAVOuterClass.HoldingNAV DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new model.PortfolioNAVOuterClass.HoldingNAV();
		}

		public static model.PortfolioNAVOuterClass.HoldingNAV getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<HoldingNAV> PARSER = new com.google.protobuf.AbstractParser<HoldingNAV>() {
			@java.lang.Override
			public HoldingNAV parsePartialFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				Builder builder = newBuilder();
				try {
					builder.mergeFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.setUnfinishedMessage(builder.buildPartial());
				} catch (com.google.protobuf.UninitializedMessageException e) {
					throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
				} catch (java.io.IOException e) {
					throw new com.google.protobuf.InvalidProtocolBufferException(e)
							.setUnfinishedMessage(builder.buildPartial());
				}
				return builder.buildPartial();
			}
		};

		public static com.google.protobuf.Parser<HoldingNAV> parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<HoldingNAV> getParserForType() {
			return PARSER;
		}

		@java.lang.Override
		public model.PortfolioNAVOuterClass.HoldingNAV getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	public interface PortfolioNAVOrBuilder extends
			// @@protoc_insertion_point(interface_extends:model.PortfolioNAV)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>string priceChangeTicker = 1;</code>
		 * 
		 * @return The priceChangeTicker.
		 */
		java.lang.String getPriceChangeTicker();

		/**
		 * <code>string priceChangeTicker = 1;</code>
		 * 
		 * @return The bytes for priceChangeTicker.
		 */
		com.google.protobuf.ByteString getPriceChangeTickerBytes();

		/**
		 * <code>double priceChangeValue = 2;</code>
		 * 
		 * @return The priceChangeValue.
		 */
		double getPriceChangeValue();

		/**
		 * <code>repeated .model.HoldingNAV holding = 3;</code>
		 */
		java.util.List<model.PortfolioNAVOuterClass.HoldingNAV> getHoldingList();

		/**
		 * <code>repeated .model.HoldingNAV holding = 3;</code>
		 */
		model.PortfolioNAVOuterClass.HoldingNAV getHolding(int index);

		/**
		 * <code>repeated .model.HoldingNAV holding = 3;</code>
		 */
		int getHoldingCount();

		/**
		 * <code>repeated .model.HoldingNAV holding = 3;</code>
		 */
		java.util.List<? extends model.PortfolioNAVOuterClass.HoldingNAVOrBuilder> getHoldingOrBuilderList();

		/**
		 * <code>repeated .model.HoldingNAV holding = 3;</code>
		 */
		model.PortfolioNAVOuterClass.HoldingNAVOrBuilder getHoldingOrBuilder(int index);

		/**
		 * <code>double value = 4;</code>
		 * 
		 * @return The value.
		 */
		double getValue();

		/**
		 * <code>int32 priceChangeCount = 5;</code>
		 * 
		 * @return The priceChangeCount.
		 */
		int getPriceChangeCount();
	}

	/**
	 * Protobuf type {@code model.PortfolioNAV}
	 */
	public static final class PortfolioNAV extends com.google.protobuf.GeneratedMessage implements
			// @@protoc_insertion_point(message_implements:model.PortfolioNAV)
			PortfolioNAVOrBuilder {
		private static final long serialVersionUID = 0L;
		static {
			com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
					com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
					/* major= */ 4, /* minor= */ 29, /* patch= */ 1,
					/* suffix= */ "", PortfolioNAV.class.getName());
		}

		// Use PortfolioNAV.newBuilder() to construct.
		private PortfolioNAV(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
			super(builder);
		}

		private PortfolioNAV() {
			priceChangeTicker_ = "";
			holding_ = java.util.Collections.emptyList();
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return model.PortfolioNAVOuterClass.internal_static_model_PortfolioNAV_descriptor;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return model.PortfolioNAVOuterClass.internal_static_model_PortfolioNAV_fieldAccessorTable
					.ensureFieldAccessorsInitialized(model.PortfolioNAVOuterClass.PortfolioNAV.class,
							model.PortfolioNAVOuterClass.PortfolioNAV.Builder.class);
		}

		public static final int PRICECHANGETICKER_FIELD_NUMBER = 1;
		@SuppressWarnings("serial")
		private volatile java.lang.Object priceChangeTicker_ = "";

		/**
		 * <code>string priceChangeTicker = 1;</code>
		 * 
		 * @return The priceChangeTicker.
		 */
		@java.lang.Override
		public java.lang.String getPriceChangeTicker() {
			java.lang.Object ref = priceChangeTicker_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				priceChangeTicker_ = s;
				return s;
			}
		}

		/**
		 * <code>string priceChangeTicker = 1;</code>
		 * 
		 * @return The bytes for priceChangeTicker.
		 */
		@java.lang.Override
		public com.google.protobuf.ByteString getPriceChangeTickerBytes() {
			java.lang.Object ref = priceChangeTicker_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				priceChangeTicker_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int PRICECHANGEVALUE_FIELD_NUMBER = 2;
		private double priceChangeValue_ = 0D;

		/**
		 * <code>double priceChangeValue = 2;</code>
		 * 
		 * @return The priceChangeValue.
		 */
		@java.lang.Override
		public double getPriceChangeValue() {
			return priceChangeValue_;
		}

		public static final int HOLDING_FIELD_NUMBER = 3;
		@SuppressWarnings("serial")
		private java.util.List<model.PortfolioNAVOuterClass.HoldingNAV> holding_;

		/**
		 * <code>repeated .model.HoldingNAV holding = 3;</code>
		 */
		@java.lang.Override
		public java.util.List<model.PortfolioNAVOuterClass.HoldingNAV> getHoldingList() {
			return holding_;
		}

		/**
		 * <code>repeated .model.HoldingNAV holding = 3;</code>
		 */
		@java.lang.Override
		public java.util.List<? extends model.PortfolioNAVOuterClass.HoldingNAVOrBuilder> getHoldingOrBuilderList() {
			return holding_;
		}

		/**
		 * <code>repeated .model.HoldingNAV holding = 3;</code>
		 */
		@java.lang.Override
		public int getHoldingCount() {
			return holding_.size();
		}

		/**
		 * <code>repeated .model.HoldingNAV holding = 3;</code>
		 */
		@java.lang.Override
		public model.PortfolioNAVOuterClass.HoldingNAV getHolding(int index) {
			return holding_.get(index);
		}

		/**
		 * <code>repeated .model.HoldingNAV holding = 3;</code>
		 */
		@java.lang.Override
		public model.PortfolioNAVOuterClass.HoldingNAVOrBuilder getHoldingOrBuilder(int index) {
			return holding_.get(index);
		}

		public static final int VALUE_FIELD_NUMBER = 4;
		private double value_ = 0D;

		/**
		 * <code>double value = 4;</code>
		 * 
		 * @return The value.
		 */
		@java.lang.Override
		public double getValue() {
			return value_;
		}

		public static final int PRICECHANGECOUNT_FIELD_NUMBER = 5;
		private int priceChangeCount_ = 0;

		/**
		 * <code>int32 priceChangeCount = 5;</code>
		 * 
		 * @return The priceChangeCount.
		 */
		@java.lang.Override
		public int getPriceChangeCount() {
			return priceChangeCount_;
		}

		private byte memoizedIsInitialized = -1;

		@java.lang.Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			memoizedIsInitialized = 1;
			return true;
		}

		@java.lang.Override
		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			if (!com.google.protobuf.GeneratedMessage.isStringEmpty(priceChangeTicker_)) {
				com.google.protobuf.GeneratedMessage.writeString(output, 1, priceChangeTicker_);
			}
			if (java.lang.Double.doubleToRawLongBits(priceChangeValue_) != 0) {
				output.writeDouble(2, priceChangeValue_);
			}
			for (int i = 0; i < holding_.size(); i++) {
				output.writeMessage(3, holding_.get(i));
			}
			if (java.lang.Double.doubleToRawLongBits(value_) != 0) {
				output.writeDouble(4, value_);
			}
			if (priceChangeCount_ != 0) {
				output.writeInt32(5, priceChangeCount_);
			}
			getUnknownFields().writeTo(output);
		}

		@java.lang.Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1)
				return size;

			size = 0;
			if (!com.google.protobuf.GeneratedMessage.isStringEmpty(priceChangeTicker_)) {
				size += com.google.protobuf.GeneratedMessage.computeStringSize(1, priceChangeTicker_);
			}
			if (java.lang.Double.doubleToRawLongBits(priceChangeValue_) != 0) {
				size += com.google.protobuf.CodedOutputStream.computeDoubleSize(2, priceChangeValue_);
			}
			for (int i = 0; i < holding_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(3, holding_.get(i));
			}
			if (java.lang.Double.doubleToRawLongBits(value_) != 0) {
				size += com.google.protobuf.CodedOutputStream.computeDoubleSize(4, value_);
			}
			if (priceChangeCount_ != 0) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(5, priceChangeCount_);
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof model.PortfolioNAVOuterClass.PortfolioNAV)) {
				return super.equals(obj);
			}
			model.PortfolioNAVOuterClass.PortfolioNAV other = (model.PortfolioNAVOuterClass.PortfolioNAV) obj;

			if (!getPriceChangeTicker().equals(other.getPriceChangeTicker()))
				return false;
			if (java.lang.Double.doubleToLongBits(getPriceChangeValue()) != java.lang.Double
					.doubleToLongBits(other.getPriceChangeValue()))
				return false;
			if (!getHoldingList().equals(other.getHoldingList()))
				return false;
			if (java.lang.Double.doubleToLongBits(getValue()) != java.lang.Double.doubleToLongBits(other.getValue()))
				return false;
			if (getPriceChangeCount() != other.getPriceChangeCount())
				return false;
			if (!getUnknownFields().equals(other.getUnknownFields()))
				return false;
			return true;
		}

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			hash = (37 * hash) + PRICECHANGETICKER_FIELD_NUMBER;
			hash = (53 * hash) + getPriceChangeTicker().hashCode();
			hash = (37 * hash) + PRICECHANGEVALUE_FIELD_NUMBER;
			hash = (53 * hash)
					+ com.google.protobuf.Internal.hashLong(java.lang.Double.doubleToLongBits(getPriceChangeValue()));
			if (getHoldingCount() > 0) {
				hash = (37 * hash) + HOLDING_FIELD_NUMBER;
				hash = (53 * hash) + getHoldingList().hashCode();
			}
			hash = (37 * hash) + VALUE_FIELD_NUMBER;
			hash = (53 * hash) + com.google.protobuf.Internal.hashLong(java.lang.Double.doubleToLongBits(getValue()));
			hash = (37 * hash) + PRICECHANGECOUNT_FIELD_NUMBER;
			hash = (53 * hash) + getPriceChangeCount();
			hash = (29 * hash) + getUnknownFields().hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static model.PortfolioNAVOuterClass.PortfolioNAV parseFrom(java.nio.ByteBuffer data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static model.PortfolioNAVOuterClass.PortfolioNAV parseFrom(java.nio.ByteBuffer data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static model.PortfolioNAVOuterClass.PortfolioNAV parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static model.PortfolioNAVOuterClass.PortfolioNAV parseFrom(com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static model.PortfolioNAVOuterClass.PortfolioNAV parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static model.PortfolioNAVOuterClass.PortfolioNAV parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static model.PortfolioNAVOuterClass.PortfolioNAV parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
		}

		public static model.PortfolioNAVOuterClass.PortfolioNAV parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static model.PortfolioNAVOuterClass.PortfolioNAV parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
		}

		public static model.PortfolioNAVOuterClass.PortfolioNAV parseDelimitedFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
		}

		public static model.PortfolioNAVOuterClass.PortfolioNAV parseFrom(com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
		}

		public static model.PortfolioNAVOuterClass.PortfolioNAV parseFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
		}

		@java.lang.Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(model.PortfolioNAVOuterClass.PortfolioNAV prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		@java.lang.Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code model.PortfolioNAV}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:model.PortfolioNAV)
				model.PortfolioNAVOuterClass.PortfolioNAVOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return model.PortfolioNAVOuterClass.internal_static_model_PortfolioNAV_descriptor;
			}

			@java.lang.Override
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return model.PortfolioNAVOuterClass.internal_static_model_PortfolioNAV_fieldAccessorTable
						.ensureFieldAccessorsInitialized(model.PortfolioNAVOuterClass.PortfolioNAV.class,
								model.PortfolioNAVOuterClass.PortfolioNAV.Builder.class);
			}

			// Construct using
			// model.PortfolioNAVOuterClass.PortfolioNAV.newBuilder()
			private Builder() {

			}

			private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				super(parent);

			}

			@java.lang.Override
			public Builder clear() {
				super.clear();
				bitField0_ = 0;
				priceChangeTicker_ = "";
				priceChangeValue_ = 0D;
				if (holdingBuilder_ == null) {
					holding_ = java.util.Collections.emptyList();
				} else {
					holding_ = null;
					holdingBuilder_.clear();
				}
				bitField0_ = (bitField0_ & ~0x00000004);
				value_ = 0D;
				priceChangeCount_ = 0;
				return this;
			}

			@java.lang.Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return model.PortfolioNAVOuterClass.internal_static_model_PortfolioNAV_descriptor;
			}

			@java.lang.Override
			public model.PortfolioNAVOuterClass.PortfolioNAV getDefaultInstanceForType() {
				return model.PortfolioNAVOuterClass.PortfolioNAV.getDefaultInstance();
			}

			@java.lang.Override
			public model.PortfolioNAVOuterClass.PortfolioNAV build() {
				model.PortfolioNAVOuterClass.PortfolioNAV result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@java.lang.Override
			public model.PortfolioNAVOuterClass.PortfolioNAV buildPartial() {
				model.PortfolioNAVOuterClass.PortfolioNAV result = new model.PortfolioNAVOuterClass.PortfolioNAV(this);
				buildPartialRepeatedFields(result);
				if (bitField0_ != 0) {
					buildPartial0(result);
				}
				onBuilt();
				return result;
			}

			private void buildPartialRepeatedFields(model.PortfolioNAVOuterClass.PortfolioNAV result) {
				if (holdingBuilder_ == null) {
					if (((bitField0_ & 0x00000004) != 0)) {
						holding_ = java.util.Collections.unmodifiableList(holding_);
						bitField0_ = (bitField0_ & ~0x00000004);
					}
					result.holding_ = holding_;
				} else {
					result.holding_ = holdingBuilder_.build();
				}
			}

			private void buildPartial0(model.PortfolioNAVOuterClass.PortfolioNAV result) {
				int from_bitField0_ = bitField0_;
				if (((from_bitField0_ & 0x00000001) != 0)) {
					result.priceChangeTicker_ = priceChangeTicker_;
				}
				if (((from_bitField0_ & 0x00000002) != 0)) {
					result.priceChangeValue_ = priceChangeValue_;
				}
				if (((from_bitField0_ & 0x00000008) != 0)) {
					result.value_ = value_;
				}
				if (((from_bitField0_ & 0x00000010) != 0)) {
					result.priceChangeCount_ = priceChangeCount_;
				}
			}

			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof model.PortfolioNAVOuterClass.PortfolioNAV) {
					return mergeFrom((model.PortfolioNAVOuterClass.PortfolioNAV) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(model.PortfolioNAVOuterClass.PortfolioNAV other) {
				if (other == model.PortfolioNAVOuterClass.PortfolioNAV.getDefaultInstance())
					return this;
				if (!other.getPriceChangeTicker().isEmpty()) {
					priceChangeTicker_ = other.priceChangeTicker_;
					bitField0_ |= 0x00000001;
					onChanged();
				}
				if (other.getPriceChangeValue() != 0D) {
					setPriceChangeValue(other.getPriceChangeValue());
				}
				if (holdingBuilder_ == null) {
					if (!other.holding_.isEmpty()) {
						if (holding_.isEmpty()) {
							holding_ = other.holding_;
							bitField0_ = (bitField0_ & ~0x00000004);
						} else {
							ensureHoldingIsMutable();
							holding_.addAll(other.holding_);
						}
						onChanged();
					}
				} else {
					if (!other.holding_.isEmpty()) {
						if (holdingBuilder_.isEmpty()) {
							holdingBuilder_.dispose();
							holdingBuilder_ = null;
							holding_ = other.holding_;
							bitField0_ = (bitField0_ & ~0x00000004);
							holdingBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders
									? getHoldingFieldBuilder()
									: null;
						} else {
							holdingBuilder_.addAllMessages(other.holding_);
						}
					}
				}
				if (other.getValue() != 0D) {
					setValue(other.getValue());
				}
				if (other.getPriceChangeCount() != 0) {
					setPriceChangeCount(other.getPriceChangeCount());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				onChanged();
				return this;
			}

			@java.lang.Override
			public final boolean isInitialized() {
				return true;
			}

			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				if (extensionRegistry == null) {
					throw new java.lang.NullPointerException();
				}
				try {
					boolean done = false;
					while (!done) {
						int tag = input.readTag();
						switch (tag) {
						case 0:
							done = true;
							break;
						case 10: {
							priceChangeTicker_ = input.readStringRequireUtf8();
							bitField0_ |= 0x00000001;
							break;
						} // case 10
						case 17: {
							priceChangeValue_ = input.readDouble();
							bitField0_ |= 0x00000002;
							break;
						} // case 17
						case 26: {
							model.PortfolioNAVOuterClass.HoldingNAV m = input
									.readMessage(model.PortfolioNAVOuterClass.HoldingNAV.parser(), extensionRegistry);
							if (holdingBuilder_ == null) {
								ensureHoldingIsMutable();
								holding_.add(m);
							} else {
								holdingBuilder_.addMessage(m);
							}
							break;
						} // case 26
						case 33: {
							value_ = input.readDouble();
							bitField0_ |= 0x00000008;
							break;
						} // case 33
						case 40: {
							priceChangeCount_ = input.readInt32();
							bitField0_ |= 0x00000010;
							break;
						} // case 40
						default: {
							if (!super.parseUnknownField(input, extensionRegistry, tag)) {
								done = true; // was an endgroup tag
							}
							break;
						} // default:
						} // switch (tag)
					} // while (!done)
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.unwrapIOException();
				} finally {
					onChanged();
				} // finally
				return this;
			}

			private int bitField0_;

			private java.lang.Object priceChangeTicker_ = "";

			/**
			 * <code>string priceChangeTicker = 1;</code>
			 * 
			 * @return The priceChangeTicker.
			 */
			public java.lang.String getPriceChangeTicker() {
				java.lang.Object ref = priceChangeTicker_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					priceChangeTicker_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string priceChangeTicker = 1;</code>
			 * 
			 * @return The bytes for priceChangeTicker.
			 */
			public com.google.protobuf.ByteString getPriceChangeTickerBytes() {
				java.lang.Object ref = priceChangeTicker_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					priceChangeTicker_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string priceChangeTicker = 1;</code>
			 * 
			 * @param value
			 *            The priceChangeTicker to set.
			 * @return This builder for chaining.
			 */
			public Builder setPriceChangeTicker(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				priceChangeTicker_ = value;
				bitField0_ |= 0x00000001;
				onChanged();
				return this;
			}

			/**
			 * <code>string priceChangeTicker = 1;</code>
			 * 
			 * @return This builder for chaining.
			 */
			public Builder clearPriceChangeTicker() {
				priceChangeTicker_ = getDefaultInstance().getPriceChangeTicker();
				bitField0_ = (bitField0_ & ~0x00000001);
				onChanged();
				return this;
			}

			/**
			 * <code>string priceChangeTicker = 1;</code>
			 * 
			 * @param value
			 *            The bytes for priceChangeTicker to set.
			 * @return This builder for chaining.
			 */
			public Builder setPriceChangeTickerBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);
				priceChangeTicker_ = value;
				bitField0_ |= 0x00000001;
				onChanged();
				return this;
			}

			private double priceChangeValue_;

			/**
			 * <code>double priceChangeValue = 2;</code>
			 * 
			 * @return The priceChangeValue.
			 */
			@java.lang.Override
			public double getPriceChangeValue() {
				return priceChangeValue_;
			}

			/**
			 * <code>double priceChangeValue = 2;</code>
			 * 
			 * @param value
			 *            The priceChangeValue to set.
			 * @return This builder for chaining.
			 */
			public Builder setPriceChangeValue(double value) {

				priceChangeValue_ = value;
				bitField0_ |= 0x00000002;
				onChanged();
				return this;
			}

			/**
			 * <code>double priceChangeValue = 2;</code>
			 * 
			 * @return This builder for chaining.
			 */
			public Builder clearPriceChangeValue() {
				bitField0_ = (bitField0_ & ~0x00000002);
				priceChangeValue_ = 0D;
				onChanged();
				return this;
			}

			private java.util.List<model.PortfolioNAVOuterClass.HoldingNAV> holding_ = java.util.Collections
					.emptyList();

			private void ensureHoldingIsMutable() {
				if (!((bitField0_ & 0x00000004) != 0)) {
					holding_ = new java.util.ArrayList<model.PortfolioNAVOuterClass.HoldingNAV>(holding_);
					bitField0_ |= 0x00000004;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilder<model.PortfolioNAVOuterClass.HoldingNAV, model.PortfolioNAVOuterClass.HoldingNAV.Builder, model.PortfolioNAVOuterClass.HoldingNAVOrBuilder> holdingBuilder_;

			/**
			 * <code>repeated .model.HoldingNAV holding = 3;</code>
			 */
			public java.util.List<model.PortfolioNAVOuterClass.HoldingNAV> getHoldingList() {
				if (holdingBuilder_ == null) {
					return java.util.Collections.unmodifiableList(holding_);
				} else {
					return holdingBuilder_.getMessageList();
				}
			}

			/**
			 * <code>repeated .model.HoldingNAV holding = 3;</code>
			 */
			public int getHoldingCount() {
				if (holdingBuilder_ == null) {
					return holding_.size();
				} else {
					return holdingBuilder_.getCount();
				}
			}

			/**
			 * <code>repeated .model.HoldingNAV holding = 3;</code>
			 */
			public model.PortfolioNAVOuterClass.HoldingNAV getHolding(int index) {
				if (holdingBuilder_ == null) {
					return holding_.get(index);
				} else {
					return holdingBuilder_.getMessage(index);
				}
			}

			/**
			 * <code>repeated .model.HoldingNAV holding = 3;</code>
			 */
			public Builder setHolding(int index, model.PortfolioNAVOuterClass.HoldingNAV value) {
				if (holdingBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureHoldingIsMutable();
					holding_.set(index, value);
					onChanged();
				} else {
					holdingBuilder_.setMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .model.HoldingNAV holding = 3;</code>
			 */
			public Builder setHolding(int index, model.PortfolioNAVOuterClass.HoldingNAV.Builder builderForValue) {
				if (holdingBuilder_ == null) {
					ensureHoldingIsMutable();
					holding_.set(index, builderForValue.build());
					onChanged();
				} else {
					holdingBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .model.HoldingNAV holding = 3;</code>
			 */
			public Builder addHolding(model.PortfolioNAVOuterClass.HoldingNAV value) {
				if (holdingBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureHoldingIsMutable();
					holding_.add(value);
					onChanged();
				} else {
					holdingBuilder_.addMessage(value);
				}
				return this;
			}

			/**
			 * <code>repeated .model.HoldingNAV holding = 3;</code>
			 */
			public Builder addHolding(int index, model.PortfolioNAVOuterClass.HoldingNAV value) {
				if (holdingBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureHoldingIsMutable();
					holding_.add(index, value);
					onChanged();
				} else {
					holdingBuilder_.addMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .model.HoldingNAV holding = 3;</code>
			 */
			public Builder addHolding(model.PortfolioNAVOuterClass.HoldingNAV.Builder builderForValue) {
				if (holdingBuilder_ == null) {
					ensureHoldingIsMutable();
					holding_.add(builderForValue.build());
					onChanged();
				} else {
					holdingBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .model.HoldingNAV holding = 3;</code>
			 */
			public Builder addHolding(int index, model.PortfolioNAVOuterClass.HoldingNAV.Builder builderForValue) {
				if (holdingBuilder_ == null) {
					ensureHoldingIsMutable();
					holding_.add(index, builderForValue.build());
					onChanged();
				} else {
					holdingBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .model.HoldingNAV holding = 3;</code>
			 */
			public Builder addAllHolding(java.lang.Iterable<? extends model.PortfolioNAVOuterClass.HoldingNAV> values) {
				if (holdingBuilder_ == null) {
					ensureHoldingIsMutable();
					com.google.protobuf.AbstractMessageLite.Builder.addAll(values, holding_);
					onChanged();
				} else {
					holdingBuilder_.addAllMessages(values);
				}
				return this;
			}

			/**
			 * <code>repeated .model.HoldingNAV holding = 3;</code>
			 */
			public Builder clearHolding() {
				if (holdingBuilder_ == null) {
					holding_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000004);
					onChanged();
				} else {
					holdingBuilder_.clear();
				}
				return this;
			}

			/**
			 * <code>repeated .model.HoldingNAV holding = 3;</code>
			 */
			public Builder removeHolding(int index) {
				if (holdingBuilder_ == null) {
					ensureHoldingIsMutable();
					holding_.remove(index);
					onChanged();
				} else {
					holdingBuilder_.remove(index);
				}
				return this;
			}

			/**
			 * <code>repeated .model.HoldingNAV holding = 3;</code>
			 */
			public model.PortfolioNAVOuterClass.HoldingNAV.Builder getHoldingBuilder(int index) {
				return getHoldingFieldBuilder().getBuilder(index);
			}

			/**
			 * <code>repeated .model.HoldingNAV holding = 3;</code>
			 */
			public model.PortfolioNAVOuterClass.HoldingNAVOrBuilder getHoldingOrBuilder(int index) {
				if (holdingBuilder_ == null) {
					return holding_.get(index);
				} else {
					return holdingBuilder_.getMessageOrBuilder(index);
				}
			}

			/**
			 * <code>repeated .model.HoldingNAV holding = 3;</code>
			 */
			public java.util.List<? extends model.PortfolioNAVOuterClass.HoldingNAVOrBuilder> getHoldingOrBuilderList() {
				if (holdingBuilder_ != null) {
					return holdingBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(holding_);
				}
			}

			/**
			 * <code>repeated .model.HoldingNAV holding = 3;</code>
			 */
			public model.PortfolioNAVOuterClass.HoldingNAV.Builder addHoldingBuilder() {
				return getHoldingFieldBuilder()
						.addBuilder(model.PortfolioNAVOuterClass.HoldingNAV.getDefaultInstance());
			}

			/**
			 * <code>repeated .model.HoldingNAV holding = 3;</code>
			 */
			public model.PortfolioNAVOuterClass.HoldingNAV.Builder addHoldingBuilder(int index) {
				return getHoldingFieldBuilder().addBuilder(index,
						model.PortfolioNAVOuterClass.HoldingNAV.getDefaultInstance());
			}

			/**
			 * <code>repeated .model.HoldingNAV holding = 3;</code>
			 */
			public java.util.List<model.PortfolioNAVOuterClass.HoldingNAV.Builder> getHoldingBuilderList() {
				return getHoldingFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilder<model.PortfolioNAVOuterClass.HoldingNAV, model.PortfolioNAVOuterClass.HoldingNAV.Builder, model.PortfolioNAVOuterClass.HoldingNAVOrBuilder> getHoldingFieldBuilder() {
				if (holdingBuilder_ == null) {
					holdingBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<model.PortfolioNAVOuterClass.HoldingNAV, model.PortfolioNAVOuterClass.HoldingNAV.Builder, model.PortfolioNAVOuterClass.HoldingNAVOrBuilder>(
							holding_, ((bitField0_ & 0x00000004) != 0), getParentForChildren(), isClean());
					holding_ = null;
				}
				return holdingBuilder_;
			}

			private double value_;

			/**
			 * <code>double value = 4;</code>
			 * 
			 * @return The value.
			 */
			@java.lang.Override
			public double getValue() {
				return value_;
			}

			/**
			 * <code>double value = 4;</code>
			 * 
			 * @param value
			 *            The value to set.
			 * @return This builder for chaining.
			 */
			public Builder setValue(double value) {

				value_ = value;
				bitField0_ |= 0x00000008;
				onChanged();
				return this;
			}

			/**
			 * <code>double value = 4;</code>
			 * 
			 * @return This builder for chaining.
			 */
			public Builder clearValue() {
				bitField0_ = (bitField0_ & ~0x00000008);
				value_ = 0D;
				onChanged();
				return this;
			}

			private int priceChangeCount_;

			/**
			 * <code>int32 priceChangeCount = 5;</code>
			 * 
			 * @return The priceChangeCount.
			 */
			@java.lang.Override
			public int getPriceChangeCount() {
				return priceChangeCount_;
			}

			/**
			 * <code>int32 priceChangeCount = 5;</code>
			 * 
			 * @param value
			 *            The priceChangeCount to set.
			 * @return This builder for chaining.
			 */
			public Builder setPriceChangeCount(int value) {

				priceChangeCount_ = value;
				bitField0_ |= 0x00000010;
				onChanged();
				return this;
			}

			/**
			 * <code>int32 priceChangeCount = 5;</code>
			 * 
			 * @return This builder for chaining.
			 */
			public Builder clearPriceChangeCount() {
				bitField0_ = (bitField0_ & ~0x00000010);
				priceChangeCount_ = 0;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:model.PortfolioNAV)
		}

		// @@protoc_insertion_point(class_scope:model.PortfolioNAV)
		private static final model.PortfolioNAVOuterClass.PortfolioNAV DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new model.PortfolioNAVOuterClass.PortfolioNAV();
		}

		public static model.PortfolioNAVOuterClass.PortfolioNAV getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<PortfolioNAV> PARSER = new com.google.protobuf.AbstractParser<PortfolioNAV>() {
			@java.lang.Override
			public PortfolioNAV parsePartialFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				Builder builder = newBuilder();
				try {
					builder.mergeFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.setUnfinishedMessage(builder.buildPartial());
				} catch (com.google.protobuf.UninitializedMessageException e) {
					throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
				} catch (java.io.IOException e) {
					throw new com.google.protobuf.InvalidProtocolBufferException(e)
							.setUnfinishedMessage(builder.buildPartial());
				}
				return builder.buildPartial();
			}
		};

		public static com.google.protobuf.Parser<PortfolioNAV> parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<PortfolioNAV> getParserForType() {
			return PARSER;
		}

		@java.lang.Override
		public model.PortfolioNAVOuterClass.PortfolioNAV getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	private static final com.google.protobuf.Descriptors.Descriptor internal_static_model_HoldingNAV_descriptor;
	private static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_model_HoldingNAV_fieldAccessorTable;
	private static final com.google.protobuf.Descriptors.Descriptor internal_static_model_PortfolioNAV_descriptor;
	private static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_model_PortfolioNAV_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n!src/main/proto/PortfolioNAV.proto\022\005mod"
				+ "el\"L\n\nHoldingNAV\022\016\n\006symbol\030\001 \001(\t\022\r\n\005pric"
				+ "e\030\002 \001(\001\022\020\n\010quantity\030\003 \001(\001\022\r\n\005value\030\004 \001(\001"
				+ "\"\220\001\n\014PortfolioNAV\022\031\n\021priceChangeTicker\030\001"
				+ " \001(\t\022\030\n\020priceChangeValue\030\002 \001(\001\022\"\n\007holdin"
				+ "g\030\003 \003(\0132\021.model.HoldingNAV\022\r\n\005value\030\004 \001("
				+ "\001\022\030\n\020priceChangeCount\030\005 \001(\005b\006proto3" };
		descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[] {});
		internal_static_model_HoldingNAV_descriptor = getDescriptor().getMessageTypes().get(0);
		internal_static_model_HoldingNAV_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
				internal_static_model_HoldingNAV_descriptor,
				new java.lang.String[] { "Symbol", "Price", "Quantity", "Value", });
		internal_static_model_PortfolioNAV_descriptor = getDescriptor().getMessageTypes().get(1);
		internal_static_model_PortfolioNAV_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
				internal_static_model_PortfolioNAV_descriptor, new java.lang.String[] { "PriceChangeTicker",
						"PriceChangeValue", "Holding", "Value", "PriceChangeCount", });
		descriptor.resolveAllFeaturesImmutable();
	}

	// @@protoc_insertion_point(outer_class_scope)
}
